# example 2 for usage of 'make' command
# 检查 some_binary 文件是否存在

# 若不存在，执行结果是，新建文件some_binary

# 若存在，执行结果如下：
# make: `some_binary' is up to date. 

# 综上，若执行两次make命令，则会分别得到上述结果

some_binary:
	touch some_binary
